IF DB_ID('ClassControlDB') IS NULL
BEGIN
    CREATE DATABASE ClassControlDB
END

USE ClassControlDB;
GO


IF NOT EXISTS (SELECT *  FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Student')
BEGIN
    CREATE TABLE Student
    (
        Id INT IDENTITY NOT NULL,
        TokenId UNIQUEIDENTIFIER NOT NULL,
        [Name] VARCHAR (256) NOT NULL,
        [User] VARCHAR (64) NOT NULL,
        [HASH] VARCHAR (512) NOT NULL
    );

    ALTER TABLE dbo.Student ADD CONSTRAINT PK_Student_Id PRIMARY KEY(Id);
    ALTER TABLE dbo.Student ADD CONSTRAINT DF_Student_TokenId DEFAULT NEWID() FOR TokenId;
END
GO

IF NOT EXISTS (SELECT *  FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Course')
BEGIN
    CREATE TABLE Course
    (
        Id INT IDENTITY NOT NULL,
        TokenId UNIQUEIDENTIFIER NOT NULL,
        [Name] VARCHAR (256) NOT NULL,
    );

    ALTER TABLE dbo.Course ADD CONSTRAINT PK_Course_Id PRIMARY KEY(Id);
    ALTER TABLE dbo.Course ADD CONSTRAINT DF_Course_TokenId DEFAULT NEWID() FOR TokenId;
END
GO

IF NOT EXISTS (SELECT *  FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Class')
BEGIN
    CREATE TABLE Class
    (
        Id INT IDENTITY NOT NULL,
        TokenId UNIQUEIDENTIFIER NOT NULL,
        [Name] VARCHAR (64) NOT NULL,
        [Year] SMALLINT NOT NULL,
        IdCourse INT NOT NULL,
    );

    ALTER TABLE dbo.Class ADD CONSTRAINT PK_Class_Id PRIMARY KEY(Id);
    ALTER TABLE dbo.Class ADD CONSTRAINT DF_Class_TokenId DEFAULT NEWID() FOR TokenId;
    ALTER TABLE dbo.Class ADD CONSTRAINT FK_Class_IdCourse FOREIGN KEY (IdCourse) REFERENCES Course(Id);
END
GO

IF NOT EXISTS (SELECT *  FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'StudentClass')
BEGIN
    CREATE TABLE StudentClass
    (
        Id INT IDENTITY NOT NULL,
        TokenId UNIQUEIDENTIFIER NOT NULL,
        IdStudent INT NOT NULL,
        IdClass INT NOT NULL,
    );

    ALTER TABLE dbo.StudentClass ADD CONSTRAINT PK_StudentClass_Id PRIMARY KEY(Id);
    ALTER TABLE dbo.StudentClass ADD CONSTRAINT DF_StudentClass_TokenId DEFAULT NEWID() FOR TokenId;
    ALTER TABLE dbo.StudentClass ADD CONSTRAINT FK_StudentClass_IdStudent FOREIGN KEY (IdStudent) REFERENCES Student(Id);
    ALTER TABLE dbo.StudentClass ADD CONSTRAINT FK_StudentClass_IdClass FOREIGN KEY (IdClass) REFERENCES Class(Id);
END
GO

